### ISSUE TITLE
Add `gem webpacker`

### ISSUE THREAD

**Issue by Lahphim** [nimbl3/rails-templates#34]
Should we add `gem webpacker` to the `Gemfile.txt`?
Because It has some issues when trying to create a new project with React environment using webpack.

I use this command `--webpack=react`.

**Comment by olivierobert** [comment]
@Lahphim yes we could. But maybe we can add it conditionally: if the option `webpack` is passed in the rails new command then it could be added, otherwise not. How about you having a dab at it?

**Comment by olivierobert** [comment]
Implemented in #39
