### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by Lahphim** [nimbl3/rails-templates#35]
I got some warning like this:
`/spec/support/simplecov.rb:2:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
`
from this line of code:
https://github.com/nimbl3/rails-templates/blob/112521650256f11077061c3f4802f6b0527af09f/shared/rspec/support/simplecov.rb#L2

then I fix it following this document:
https://github.com/colszowka/simplecov#using-multiple-formatters

**Comment by olivierobert** [comment]
@Lahphim for everything you fixed please open a PR onto the project of `rails-templates` so that it's fixed the next time we use the template 🙇

**Comment by olivierobert** [comment]
@Lahphim any update on this? Please open a PR to fix this issue 😃

**Comment by olivierobert** [comment]
Closed by #52
