### ISSUE TITLE
Can NOT generate the template via Github URL.

### ISSUE THREAD

**Issue by Yutna** [nimbl3/rails-templates#64]
I can NOT generate the template from Github URL. I need to clone from the development branch and generate from the local files.

**Expect**
```
rails new < app_name > -m https://raw.githubusercontent.com/nimbl3/rails-templates/master/rails_docker.rb -T
```

**Actual**
```
rails new < app_name > -m ./rails-templates/rails_docker.rb -T
```

Should we change from the master branch to the development branch?

**Comment by hanam1ni** [comment]
Solved in #70
