### ISSUE TITLE
Error about `.env.test` when rails-templates generate files while bootstrap the project.

### ISSUE THREAD

**Issue by Yutna** [nimbl3/rails-templates#66]
This error occurs when you start the project by using rails-template. since the rails-templates no `.env.test` file. It has only `.env` file.

To prevent this error you must to modify the `rails_docker.rb` to this.

```ruby
# from
copy_file 'rails_docker/.env.test', '.env.test'
gsub_file '.env.test', '#{app_name}', "#{app_name}"
# to
copy_file 'rails_docker/.env', '.env'
gsub_file '.env', '#{app_name}', "#{app_name}"
```

**Comment by hanam1ni** [comment]
Solved in #70
